server:
  port: 8080

spring:
  application:
    name: api-gateway-yl
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user_service_route
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: qa_service_route
          uri: http://qa-service:8082
          predicates:
            - Path=/api/qa/**

jwt:
  secret: 63ffbc2b8d13ad5180ed7ae7c67f18c85d86046732fc9ced6a02a9d50abb1a03
  expiration:
    ms: 86400000

