services:
  # MySQL 数据库
  database:
    image: mysql:8.0
    container_name: ai-qa-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # 删除这两行！不要设置 MYSQL_USER 和 MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ai-qa-network

  # User Service - 使用 root 用户连接
  user-service:
    image: ${DOCKERHUB_USERNAME}/ai-qa-user-service:latest
    container_name: ai-qa-user-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_ROOT_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD} # 使用 root 密码
    networks:
      - ai-qa-network

  # QA Service - 使用 root 用户连接
  qa-service:
    image: ${DOCKERHUB_USERNAME}/ai-qa-qa-service:latest
    container_name: ai-qa-qa-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_ROOT_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD} # 使用 root 密码
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    networks:
      - ai-qa-network
