version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend-services
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # API网关端口
      - "8081:8081"  # User服务端口
      - "8082:8082"  # QA服务端口
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - redis
    networks:
      - ai-network

  # 前端服务
  frontend:
    build:
      context: ./fronted
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # 映射到宿主机的3000端口
    depends_on:
      - backend
    networks:
      - ai-network

  # PostgreSQL数据库
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ai_qa_system
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ai-network

  # Redis缓存
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - ai-network

# 网络和卷配置
networks:
  ai-network:
    driver: bridge

volumes:
  postgres-data:
