# version: '3.8'

services:
  api-gateway:
    image: chatbox-api-gateway:latest
    container_name: chatbox-api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - NACOS_SERVER_ADDR=3.101.113.38:8848
    networks:
      - chatbox-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  user-service:
    image: chatbox-user-service:latest
    container_name: chatbox-user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - NACOS_SERVER_ADDR=3.101.113.38:8848
    networks:
      - chatbox-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  qa-service:
    image: chatbox-qa-service:latest
    container_name: chatbox-qa-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - NACOS_SERVER_ADDR=3.101.113.38:8848
    networks:
      - chatbox-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    image: chatbox-frontend:latest
    container_name: chatbox-frontend
    ports:
      - "3000:3000"
    networks:
      - chatbox-network
    restart: unless-stopped
    depends_on:
      api-gateway:
        condition: service_healthy

networks:
  chatbox-network:
    driver: bridge
