# version: '3.8'

services:
  api-gateway:
    image: suifm/chatbox-api-gateway:latest
    ports:
      - "8080:8080"
    restart: always

  user-service:
    image: suifm/chatbox-user-service:latest
    ports:
      - "8081:8081"
    restart: always

  qa-service:
    image: suifm/chatbox-qa-service:latest
    ports:
      - "8082:8082"
    restart: always

  frontend:
    image: suifm/chatbox-frontend:latest
    ports:
      - "3000:3000"
    restart: always

networks:
  chatbox-network:
    driver: bridge
