services:
  mysql:
    image: mysql:8.0
    container_name: ai-qa-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ai_qa_system}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ai_qa_system}
      MYSQL_USER: ${MYSQL_USER:-ai_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ai_user_pass}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend-services/user-service/src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  user-service:
    build:
      context: ./backend-services
      dockerfile: user-service/Dockerfile
    container_name: ai-qa-user-service
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ai_qa_system}
      MYSQL_USER: ${MYSQL_USER:-ai_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ai_user_pass}
      NACOS_SERVER_ADDR: ${NACOS_SERVER_ADDR:-13.230.43.180:8848}
      JWT_SECRET: ${JWT_SECRET:-7zmKiI4PToMYMC9G5nuAcL5JBRBYFZCzrn7PIM4zPZY=}
    ports:
      - "8081:8081"

  qa-service:
    build:
      context: ./backend-services
      dockerfile: qa-service/Dockerfile
    container_name: ai-qa-qa-service
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ai_qa_system}
      MYSQL_USER: ${MYSQL_USER:-ai_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ai_user_pass}
      NACOS_SERVER_ADDR: ${NACOS_SERVER_ADDR:-13.230.43.180:8848}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8082:8082"

  api-gateway:
    build:
      context: ./backend-services
      dockerfile: api-gateway/Dockerfile
    container_name: ai-qa-api-gateway
    depends_on:
      - user-service
      - qa-service
    environment:
      NACOS_SERVER_ADDR: ${NACOS_SERVER_ADDR:-13.230.43.180:8848}
      SECURITY_JWT_SECRET: ${JWT_SECRET:-7zmKiI4PToMYMC9G5nuAcL5JBRBYFZCzrn7PIM4zPZY=}
    ports:
      - "8083:8083"

  frontend:
    build:
      context: ./ai-chatbot
      dockerfile: Dockerfile
    container_name: ai-qa-frontend
    depends_on:
      - api-gateway
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${FRONTEND_API_BASE_URL:-http://api-gateway:8083}
      NODE_ENV: production
    ports:
      - "3000:3000"

volumes:
  mysql-data:
    driver: local
