spring:
  application:
    name: qa-service-tyf
  cloud:
    nacos:
      discovery:
        # server-addr: 3.84.225.222:8848
        # ip: 3.84.225.222
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        ip: ${SPRING_CLOUD_NACOS_DISCOVERY_IP}
management:
  endpoints:
    web:
      exposure:
        include: health,info
