server:
  port: 8082
spring:
  application:
    name: qa-service-zjy
  # cloud:
  #   nacos:
  #     discovery:
  #       server-addr: 127.0.0.1:8848
  #     config:
  #       name: qa-service-zjy
  #       file-extension: yaml # 读取 yaml 配置
  #       group: DEFAULT_GROUP
  #       enabled: true
  datasource:
    url: jdbc:mysql://3.106.55.195:3306/ai_qa_system?useSSL=false&serverTimezone=UTC
    username: root
    password: QWE123asd
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

logging:
  file:
    name: logs/qa-service.log

google:
  ai:
    api-key: AIzaSyCGvYQa-5kJDbbXsr372wHsHBWEDtufjBM
    model: gemini-2.5-flash
    base-url: https://generativelanguage.googleapis.com/v1beta
