spring:
  application:
    name: qa-service-yl
  cloud:
    nacos:
      discovery:
        server-addr: 3.84.225.222:8848
        ip: 3.84.225.222
management:
  endpoints:
    web:
      exposure:
        include: health,info
