server:
  port: 8082

spring:
  application:
    name: qa-service-fm

  config:
    import:
      # 引入共享配置
      - "nacos:shared-config_fm.yml"
  cloud:
    nacos:
      server-addr: 3.101.113.38:8848
      config:
        # 明确告诉 Nacos Config 默认的文件扩展名是 yml
        file-extension: yml
        group: DEFAULT_GROUP

  datasource:
    url: jdbc:mysql://ai-qa-system-sfm.cj6gcogsidzt.ap-southeast-2.rds.amazonaws.com:3306/ai_qa_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ai_qa_system
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

# OpenAPI 文档配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

