server:
  port: 8081
spring:
  application:
    name: user-service-zjy
  cloud:
    nacos:
      discovery:
        server-addr: 3.106.55.195:8848
  datasource:
    url: jdbc:mysql://3.106.55.195:3306/ai_qa_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: QWE123asd
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
logging:
  file:
    name: logs/user-service.log
