name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    name: Test Configuration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate YAML files
      run: |
        echo "✅ Validating workflow files..."
        python3 -c "
        import yaml
        import sys

        files = [
            '.github/workflows/ci.yml',
            '.github/workflows/deploy.yml'
        ]

        for file in files:
            try:
                with open(file, 'r') as f:
                    yaml.safe_load(f)
                print(f'✅ {file} is valid YAML')
            except Exception as e:
                print(f'❌ {file} has YAML error: {e}')
                sys.exit(1)
        "

    - name: Check Docker Compose
      run: |
        echo "✅ Validating docker-compose.yml..."
        docker-compose config

    - name: Check Frontend Package
      run: |
        echo "✅ Validating frontend package.json..."
        cd fronted
        npm ci --dry-run

    - name: Check Backend POM
      run: |
        echo "✅ Validating backend pom.xml..."
        cd backend-services
        mvn validate -q
